# Generated by Django 4.0.4 on 2022-07-14 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recepient',
            new_name='recipient',
        ),
    ]
